#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

echo "Commit message is: $commit_msg"

# Example validation
if ! echo "$commit_msg" | grep -qE "^(feat|fix|chore|docs):"; then
  echo "❌ Invalid commit message!"
  echo "Use format: feat: message OR fix: message"
  exit 1
fi