name: "tmp workflow"
on:
  pull_request:
    branches: [develop,branch/test-pr-main]
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: script
        run: |
          echo "hello world"
          echo $GITHUB_REF_NAME
