name: "pr validation 2"
on:
  pull_request:
    branches: [develop,main]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: script
        run: |
          echo "hello world"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
