name: "pr validation 2"
on:
  pull_request:
    branches: [develop,main]
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      CURRENT_BRANCH_NAME: ${{github.ref}}
    steps:
      - name: script
        run: |
          echo "hello world"
          echo "$GITHUB_REF_NAME"
          echo "$CURRENT_BRANCH_NAME"
