name: push
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: push_task
        run: |
          echo "Hi"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
