name: "Rolback Tag Pipeline"
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to rollback'
        required: true
        default: 'v1.0.0'
jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Rollback to Tag"
        run: |
          git fetch --tags
          git checkout ${{ github.event.inputs.tag_name }}
          echo "Rolled back to tag: ${{ github.event.inputs.tag_name }}"
          cat README.md
    
